# Run workflow using API

In [1]:
from pathlib import Path

from rich import print as pprint

In [2]:
import logging

logging.basicConfig(level=logging.WARNING)
# Set to WARNING to see only warnings
# Set to INFO to see sparql queries
# Set to DEBUG to see raw results

## Setup session directory

In this directory files like PDB files are stored and a DuckDB database for meta data.

In [3]:
session_dir = Path("session1")
session_dir

PosixPath('session1')

## Search Uniprot for structures

In [4]:
from protein_detective.uniprot import Query
from protein_detective.workflow import search_structures_in_uniprot

In [5]:
query = Query(
    taxon_id="9606",
    reviewed=True,
    subcellular_location_uniprot="nucleus",
    subcellular_location_go="GO:0005634",  # Cellular component - Nucleus
    molecular_function_go="GO:0003677",  # Molecular function - DNA binding
)

In [6]:
nr_uniprot, nr_pdbe, nr_af = search_structures_in_uniprot(query, session_dir, limit=80)
nr_uniprot, nr_pdbe, nr_af

WARNING:protein_detective.uniprot:Search for uniprot accessions returned 80 results. There may be more results available, but they are not returned due to the limit of 80. Consider increasing the limit to get more results.

(55, 13, 55)

Use [database queries](#query-session-database) to see what was found.

## Fetch structures from PDBe and Alphafold found in Uniprot

In [4]:
from protein_detective.workflow import retrieve_structures

In [5]:
download_path, nr_pdbs, nr_alphafolds = retrieve_structures(session_dir)
download_path, nr_pdbs, nr_alphafolds

Downloading PDBe files: 100%|██████████| 13/13 [00:00<00:00, 54635.22it/s]
Fetching Alphafold summaries: 100%|██████████| 55/55 [00:02<00:00, 25.34it/s]
Downloading AlphaFold files: 100%|██████████| 110/110 [00:00<00:00, 66672.46it/s]

(PosixPath('session1/downloads'), 13, 55)

## Filter out AlphafoldDB structures with low confidence

And write PDB files without those low confidence residues to new directory.

In [12]:
from protein_detective.alphafold.density import DensityFilterQuery
from protein_detective.workflow import density_filter

In [13]:
dquery = DensityFilterQuery(
    confidence=70.0,
    min_threshold=100,
    max_threshold=500,
)

In [14]:
result = density_filter(session_dir, dquery)
pprint(result)

DensityFilterSessionResult(density_filtered_dir=PosixPath('session1/density_filtered'),
                           nr_kept=24,
                           nr_discarded=31)

## Prune PDBe files
Prune the PDB files to only keep the first chain of the found Uniprot entries and rename that chain to A.

In [1]:
from protein_detective.workflow import prune_pdbs

In [7]:
(single_chain_dir, nr_passed) = prune_pdbs(session_dir)
(single_chain_dir, nr_passed)

Saving single chain PDB files from PDBe: 100%|██████████| 13/13 [00:02<00:00,  5.76it/s]

(PosixPath('session1/single_chain'), 13)

## Powerfit

In [4]:
from protein_detective.powerfit.options import PowerfitOptions
from protein_detective.workflow import powerfit_commands

To run you must have cloned the https://github.com/haddocking/powerfit-tutorial repository in '../../powerfit-tutorial'.

In [5]:
options = PowerfitOptions(
    target=Path("../../powerfit-tutorial/ribosome-KsgA.map"),
    resolution=13,
    angle=20,
    laplace=True,
)

### Run

Here we use printed commands to run powerfit, see [powerfit.ipynb](powerfit.ipynb) for running powerfits using the API.

In [6]:
commands, powerfit_run_id = powerfit_commands(session_dir, options)

In [7]:
powerfit_run_id

10

In [8]:
cwd = str(Path.cwd())
rel_commands = [c.replace(cwd, ".") for c in commands]
pprint(rel_commands)

[
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb4ne5.ent_B2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb4ne5.ent_B2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb7xho.ent_X2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb7xho.ent_X2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb7r5s.ent_X2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb7r5s.ent_X2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb4ndy.ent_B2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb4ndy.ent_B2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb4ne3.ent_B2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb4ne3.ent_B2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb7ywx.ent_X2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb7ywx.ent_X2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb4e45.ent_B2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb4e45.ent_B2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb7xhn.ent_X2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb7xhn.ent_X2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb4drb.ent_J2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb4drb.ent_J2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb4ne1.ent_B2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb4ne1.ent_B2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb4e44.ent_B2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb4e44.ent_B2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb4dra.ent_E2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb4dra.ent_E2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/single_chain/A8MT69_pdb4ne6.ent_B2A.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/A8MT69_pdb4ne6.ent_B2A
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A0A087WUV0-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A0A087WUV0-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A0A0U1RQI7-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A0A0U1RQI7-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A0A1B0GTS1-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A0A1B0GTS1-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A0A1B0GWH4-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A0A1B0GWH4-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A0A1W2PPF3-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A0A1W2PPF3-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A0A1W2PQL4-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A0A1W2PQL4-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A1YPR0-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A1YPR0-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A2RRD8-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A2RRD8-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NDX5-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NDX5-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NFD8-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NFD8-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NFI3-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NFI3-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NGD5-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NGD5-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NHJ4-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NHJ4-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NJL1-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NJL1-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NJT0-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NJT0-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NK53-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NK53-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NK75-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NK75-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NKF2-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NKF2-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NLW8-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NLW8-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NM28-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NM28-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A6NP11-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A6NP11-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A8K0S8-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A8K0S8-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A8K8V0-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A8K8V0-F1-model_v4
--delimiter , --angle 20',
    'powerfit ./session1/powerfit/10/ribosome-KsgA.map 13 ./session1/density_filtered/AF-A8MT65-F1-model_v4.pdb
--laplace --resampling-rate 2 --num 10 --nproc 1 --directory ./session1/powerfit/10/AF-A8MT65-F1-model_v4
--delimiter , --angle 20'
]

These commands should be run on a cluster. Here we will just run a couple of them to show how it works.

In [9]:
!{rel_commands[6]}

Target file read from:
/home/verhoes/git/protein-detective/protein-detective/docs/session1/powerfit/10/
ribosome-KsgA.map
Target resolution: 13.00
Initial shape of density: 128 128 128
Shape after trimming: 60 73 67
Shape after extending: 60 75 70
Template file read from:
/home/verhoes/git/protein-detective/protein-detective/docs/session1/single_chain
/A8MT69_pdb4e45.ent_B2A.pdb
Reading in rotations.
Requested rotational sampling density: 20.00
Real rotational sampling density: 20.83
Requested number of processors: 1
Starting search
Processing rotations 100% ━━━━━━━━━━━━ 648/648  [ 0:00:09 < 0:00:00 , 71 rot/s ] , 71 rot/s ]m72 rot/s ]
Time for search: 0m 9s
Analyzing results
Writing solutions to file.
Writing PDBs to file.
Total time: 0m 9s

In [10]:
!{rel_commands[0]}

Target file read from:
/home/verhoes/git/protein-detective/protein-detective/docs/session1/powerfit/10/
ribosome-KsgA.map
Target resolution: 13.00
Initial shape of density: 128 128 128
Shape after trimming: 60 73 67
Shape after extending: 60 75 70
Template file read from:
/home/verhoes/git/protein-detective/protein-detective/docs/session1/single_chain
/A8MT69_pdb4ne5.ent_B2A.pdb
Reading in rotations.
Requested rotational sampling density: 20.00
Real rotational sampling density: 20.83
Requested number of processors: 1
Starting search
Processing rotations 100% ━━━━━━━━━━━╸ 647/648  [ 0:00:08 < 0:00:01 , 73 rot/s ]m73 rot/s ]
Time for search: 0m 9s
Analyzing results
Writing solutions to file.
Writing PDBs to file.
Total time: 0m 9s

In [12]:
!{rel_commands[-1]}

Target file read from:
/home/verhoes/git/protein-detective/protein-detective/docs/session1/powerfit/10/
ribosome-KsgA.map
Target resolution: 13.00
Initial shape of density: 128 128 128
Shape after trimming: 60 73 67
Shape after extending: 60 75 70
Template file read from:
/home/verhoes/git/protein-detective/protein-detective/docs/session1/density_filt
ered/AF-A8MT65-F1-model_v4.pdb
Reading in rotations.
Requested rotational sampling density: 20.00
Real rotational sampling density: 20.83
Requested number of processors: 1
Starting search
Processing rotations 100% ━━━━━━━━━━━╸ 647/648  [ 0:00:08 < 0:00:01 , 73 rot/s ]m73 rot/s ]
Time for search: 0m 9s
Analyzing results
Writing solutions to file.
Writing PDBs to file.
Total time: 0m 9s

### Report

Once all powerfit jobs are done the results can be parsed and reported.

In [4]:
from protein_detective.workflow import powerfit_report

In [5]:
solutions = powerfit_report(session_dir)

In [6]:
len(solutions)

5238

In [7]:
solutions

,powerfit_run_id,structure,rank,cc,fishz,relz,translation,rotation,density_filter_id,pdb_id,pdb_file,uniprot_acc
0,10,A8MT69_pdb4e45.ent_B2A,1,0.432,0.463,10.091,"[227.18, 242.53, 211.83]","[0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0]",<NA>,4E45,session1/single_chain/A8MT69_pdb4e45.ent_B2A.pdb,A8MT69
1,10,A8MT69_pdb4ne5.ent_B2A,1,0.423,0.452,10.053,"[227.18, 242.53, 214.9]","[0.0, -0.0, -0.0, -0.604, 0.797, 0.0, 0.797, 0...",<NA>,4NE5,session1/single_chain/A8MT69_pdb4ne5.ent_B2A.pdb,A8MT69
2,10,A8MT69_pdb7xho.ent_X2A,1,0.423,0.452,10.253,"[208.76, 193.41, 257.88]","[-0.548, 0.816, 0.816, 0.632, 0.548, -0.548, -...",<NA>,7XHO,session1/single_chain/A8MT69_pdb7xho.ent_X2A.pdb,A8MT69
3,10,A8MT69_pdb4e45.ent_B2A,2,0.418,0.445,9.705,"[224.11, 264.02, 153.5]","[0.797, 0.0, 0.0, 0.604, -0.0, -0.797, 0.0, 1....",<NA>,4E45,session1/single_chain/A8MT69_pdb4e45.ent_B2A.pdb,A8MT69
4,10,A8MT69_pdb4ne5.ent_B2A,2,0.414,0.441,9.815,"[227.18, 138.15, 227.18]","[-0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 1.0, 0.0, -0.0]",<NA>,4NE5,session1/single_chain/A8MT69_pdb4ne5.ent_B2A.pdb,A8MT69
...,...,...,...,...,...,...,...,...,...,...,...,...
5233,10,AF-A8MT65-F1-model_v4,1486,0.130,0.131,5.308,"[208.76, 257.88, 187.27]","[0.548, -0.184, -0.184, 0.548, 0.816, 0.184, 0...",1,None,session1/density_filtered/AF-A8MT65-F1-model_v...,A8MT65
5234,10,AF-A8MT65-F1-model_v4,1487,0.130,0.131,5.303,"[233.32, 174.99, 273.23]","[0.362, -0.258, -0.258, -0.258, 0.896, -0.362,...",1,None,session1/density_filtered/AF-A8MT65-F1-model_v...,A8MT65
5235,10,AF-A8MT65-F1-model_v4,1488,0.130,0.130,5.293,"[196.48, 184.2, 156.57]","[0.184, 0.548, 0.548, -0.816, 0.548, -0.184, -...",1,None,session1/density_filtered/AF-A8MT65-F1-model_v...,A8MT65
5236,10,AF-A8MT65-F1-model_v4,1489,0.129,0.130,5.280,"[239.46, 144.29, 174.99]","[-0.548, -0.632, -0.632, -0.816, 0.548, -0.184...",1,None,session1/density_filtered/AF-A8MT65-F1-model_v...,A8MT65
5237,10,AF-A8MT65-F1-model_v4,1490,0.129,0.130,5.274,"[144.29, 165.78, 236.39]","[-0.0, -1.0, -1.0, 1.0, -0.0, 0.0, 0.0, 0.0, 1.0]",1,None,session1/density_filtered/AF-A8MT65-F1-model_v...,A8MT65

### Fit structure to solution

Rotate/translate the input PDB files to the top 10 powerfit solutions.

In [4]:
from protein_detective.workflow import powerfit_fit_pdbs

In [5]:
fitted, root_fit_dir = powerfit_fit_pdbs(session_dir, top=5)
root_fit_dir

Writing fitted PDB files: 100%|██████████| 5/5 [00:00<00:00, 267.53it/s]

PosixPath('session1/fitted_pdbs')

In [6]:
fitted

,powerfit_run_id,pdb_file,fitted_file
index,,,
0,11,session1/single_chain/A8MT69_pdb4ne6.ent_B2A.pdb,session1/fitted_pdbs/1_11_A8MT69_pdb4ne6.ent_B...
1,11,session1/single_chain/A8MT69_pdb4drb.ent_J2A.pdb,session1/fitted_pdbs/2_11_A8MT69_pdb4drb.ent_J...
2,11,session1/single_chain/A8MT69_pdb4dra.ent_E2A.pdb,session1/fitted_pdbs/3_11_A8MT69_pdb4dra.ent_E...
3,11,session1/single_chain/A8MT69_pdb4e44.ent_B2A.pdb,session1/fitted_pdbs/4_11_A8MT69_pdb4e44.ent_B...
4,11,session1/single_chain/A8MT69_pdb7xhn.ent_X2A.pdb,session1/fitted_pdbs/5_11_A8MT69_pdb7xhn.ent_X...

PosixPath('session1/single_chain/A8MT69_pdb4ne6.ent_B2A.pdb')